# Generated by TerraAgent - import blocks for existing AWS resources.
# Review before use. `terraform plan` shows these as "will be imported"; nothing is
# imported until someone applies this configuration in their own pipeline.
# TerraAgent never runs apply or import.

import {
  to = aws_iam_role.aws_elasticbeanstalk_ec2_role_c4548318
  id = "aws-elasticbeanstalk-ec2-role"
}

import {
  to = aws_s3_bucket.elasticbeanstalk_ap_south_1_314900493735_e601428d
  id = "elasticbeanstalk-ap-south-1-314900493735"
}

import {
  to = aws_route_table.rtb_0e1ce943b1ad77e78_e2f8527a
  id = "rtb-0e1ce943b1ad77e78"
}

import {
  to = aws_security_group.aikart_email_agent_sg_a2c49eff
  id = "sg-01d377db9843deb12"
}

import {
  to = aws_subnet.subnet_045e107acc9b9dfff_3e9a745b
  id = "subnet-045e107acc9b9dfff"
}

import {
  to = aws_subnet.subnet_0a25b61c8743c54af_c84cc3d0
  id = "subnet-0a25b61c8743c54af"
}

import {
  to = aws_subnet.subnet_0eab8241c808097b4_46a4941e
  id = "subnet-0eab8241c808097b4"
}
