# Generated by TerraAgent - import blocks for existing AWS resources.
# Review before use. `terraform plan` shows these as "will be imported"; nothing is
# imported until someone applies this configuration in their own pipeline.
# TerraAgent never runs apply or import.

import {
  to = aws_route_table.rtb_003b648347930edfc_24811887
  id = "rtb-003b648347930edfc"
}

import {
  to = aws_subnet.subnet_02dadc23105f456c7_e02172d9
  id = "subnet-02dadc23105f456c7"
}

import {
  to = aws_subnet.subnet_05903c67b2d9cf30e_d79e046f
  id = "subnet-05903c67b2d9cf30e"
}

import {
  to = aws_subnet.subnet_09159df420049bc3a_266ccf66
  id = "subnet-09159df420049bc3a"
}

import {
  to = aws_subnet.subnet_0b6636ac6bf13e7e5_914d31f6
  id = "subnet-0b6636ac6bf13e7e5"
}

import {
  to = aws_subnet.subnet_0c3a8f6c4789c2fc0_2d098f5f
  id = "subnet-0c3a8f6c4789c2fc0"
}

import {
  to = aws_subnet.subnet_0cc33aa9e58ca5daa_0fd504a3
  id = "subnet-0cc33aa9e58ca5daa"
}
