name: "Terraform Apply (Merge to Main)"

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - "*.tf"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"
          terraform_wrapper: false

      - name: Configure AWS Credentials via OIDC (STS)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::314900493735:role/GitHubActions-TerraformDeployer
          aws-region: ap-south-1
          audience: sts.amazonaws.com
          role-session-name: github-actions-tf-apply-session

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      - name: Terraform Init
        id: init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Apply
        id: apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve -input=false -no-color